# Usa la imagen oficial de Node.js como base
FROM node:14

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de dependencias y los instala
COPY package.json package-lock.json ./
RUN npm install

# Copia el código de la aplicación al contenedor
COPY . .

# Expone el puerto que usará la aplicación
EXPOSE 3000

# Ejecuta el comando para iniciar la aplicación en modo desarrollo con hot-reloading
CMD ["npm", "run", "dev"]
